### ISSUE TITLE
Icons for keyboard-configurator inconsitant depending on location

### ISSUE THREAD

**Issue by bflanagin** [pop-os/keyboard-configurator#34] opened 2021-04-22 15:51 UTC
# Pop Version
Pop_21.04, possibly others.

#Application version
```
system76-keyboard-configurator:
  Installed: 0.1.0~1618860654~21.04~750ff7b
  Candidate: 0.1.0~1618860654~21.04~750ff7b
  Version table:
 *** 0.1.0~1618860654~21.04~750ff7b 100
        100 /var/lib/dpkg/status
```
The application Icon shows up in the dock.

![Screenshot from 2021-04-22 10-46-20](https://user-images.githubusercontent.com/10382037/115744690-6dd42000-a358-11eb-9f5f-b99f25a7cc65.png)

But not in the launcher or the app grid/app wall.

![Screenshot from 2021-04-22 10-46-12](https://user-images.githubusercontent.com/10382037/115744693-6dd42000-a358-11eb-8a57-151d517bfeed.png)

**Comment by ids1024** [comment] 2021-04-22 16:21
This should be fixed once https://github.com/pop-os/keyboard-configurator/commit/7bb04ee89a42646e25604d18bc7dc33baa6d7945 is built.

**Comment by ids1024** [comment] 2021-05-03 21:57
Closing. Can be reopened if the problem is observed again.

**Closed by ids1024** 2021-05-03 21:57 UTC
