### ISSUE TITLE
[Feature request] Allow assigning macros to single key

### ISSUE THREAD

**Issue by Leniwcowaty** [pop-os/keyboard-configurator#246] opened 2024-11-27 00:36 UTC
Originally I wanted to ask for adding stuff like "Close window" or "Minimize window". But I understand it would be really hard, as each OS, and each distro has different way of handling that.
That's why I think an easier way would be to add ability to assign macros. So I could map my Q at layer 2 to "Alt+F4", so on Launch Lite I only have to press "Fn+Q" instead of "Fn+Alt+4" to close window.
Would that be an option?

**Comment by leviport** [comment] 2024-11-27 15:04
Duplicate of https://github.com/pop-os/keyboard-configurator/issues/146

**Closed by leviport** 2024-11-27 15:04 UTC
