### ISSUE TITLE
Feature Request: Macros

### ISSUE THREAD

**Issue by DarkArc** [pop-os/keyboard-configurator#213] opened 2023-09-12 02:11 UTC
It would be nice to have macro support.

One thing I miss from my Moonlander is the ability to create macros to activate system shortcuts, e.g. presenting windows, activating the desktop search, muting the microphone, etc

**Comment by leviport** [comment] 2023-09-12 15:07
Duplicate of https://github.com/pop-os/keyboard-configurator/issues/146

**Closed by leviport** 2023-09-12 15:07 UTC
